fannheyward/coc-pyright

- README.md
It seems coc-pyright supports all pyright settings right?
https://github.com/microsoft/pyright/blob/master/docs/settings.md
> Add link to Pyright Settings

- package.json
Description
-------------------------------------------------------
Adjusted the configuration based on the latest [package.json](https://github.com/microsoft/pyright/blob/master/packages/vscode-pyright/package.json) of `pyright`
Update configuration options
-------------------------------------------------------
- Fix `reportWildcardImportFromLibrary` from `none` to `warning`
- REF: https://github.com/microsoft/pyright/commit/f72711b07bd38b3bc719ad353c9419e45d8c7d5d
- `reportImplicitStringConcatenation` has been changed from `warning` to `none`
- REF: https://github.com/microsoft/pyright/commit/9e46548fc524f8aba206c1684d76a5b3a7809d35
- The value of enum in `python.analysis.logLevel` has been changed, e.g: from `error` to `Error`, from `info` to `Infomartion` and more.
- REF: …
> Adjusted the configuration options

- yarn.lock
Installing the current master with `yarn install --frozen-lockfile` fails:
```
$ yarn install --frozen-lockfile
yarn install v1.22.10
[1/5] 🔍  Validating package.json...
warning coc-pyright@1.1.108: The engine "coc" appears to be invalid.
[2/5] 🔍  Resolving packages...
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
This PR updates the lockfile by running `yarn install`.
> Fix installing with --frozen-lockfile

- README.md
- package.json
- src/index.ts
Added an option to enable/disable the coc-pyright extension.
This is used when you want to use other Python-related extensions besides coc-pyright at the project level.
For example, you may want to use `coc-jedi`, and your linter or formatter may use `coc-diagnostic`.
In such cases, it is useful to have an option to enable/disable the coc-pyright extension.
If you have not intentionally added an enable/disable option setting, please close this PR. 🙇
> Add "pyright.enable" option

- src/configSettings.ts
Changes:
- disable ANSI output for poetry with `--no-ansi`, otherwise we get redundant characters in Python path:
```
^[[34mC:\Users\gerald\Git\ocr\.venv ^[[0m
```
- resolve Python path correctly in Windows, which should be `.venv/Scripts/python.exe`.
> fix: support venv in Windows

- src/codeActionsProvider.ts
close #404
----
**Before**:
```python
def dummy() -> None:
return "dummy" # type: ignore
```
**After**:
two space.
```python
def dummy() -> None:
return "dummy"  # type: ignore
```
> fix: Change to add two spaces in the "ignore action for current line"

- src/configSettings.ts
This adds support for finding and setting the correct `pythonPath` if there's a virtualenv present in the workspace root directory.
This kind of works already if `cwd == workspaceRoot` (I assume Pyright itself does the correct thing?). But if you for example do `:e ../../other-project/foo.py` it will just use the interpreter available in `$PATH` even if there's both workspace root and a virtualenv in `../../other-project`.
> feat: Detect virtualenv in workspace root

- package.json
"pyright" repository seems to have been changed from the master branch to the main branch.
Currently it redirects, but I changed it because it might not be able to connect in the future.
> chore: Change the download branch for json schema (master -> main)

- src/codeActionsProvider.ts
The issue https://github.com/fannheyward/coc-pyright/issues/404 regressed as of [this commit](https://github.com/fannheyward/coc-pyright/commit/c599f6f4d0fa53e13adc44df80bc48f904186dfe).
This corrects coc-pyright to use 2 spaces before inline "type: ignore" comments as per pep8.
> fix: 2 spaces used for inline type: ignore comment

- README.md
I just added a line in `README.md` that calls out the additional configuration settings found in `package.json`. This would have been extremely helpful for me (someone who is unfamiliar with the location of things in a project like this).
> Clarify location of other config options

- src/index.ts
Currently private member suggestions are interspersed with public ones and are rarely needed. Most implementations (e.g. pyright's sortText, pycharm) give lower priority to them.
> Give private members lower suggestion priority

- src/index.ts
I found this PR and commit on upstream, I changed coc-pyright as well.
- PR
- <https://github.com/microsoft/pyright/pull/3072>
- commit
- <https://github.com/microsoft/pyright/commit/c56d750d74571cae86587931d85353d4ce28bf19>
Some memory issues may be alleviated.
> perf: changed the default "max heap size" from 1.7GB to 3.0GB

- src/features/inlayHints.ts
The inlay hints in `coc-pyright-tools` were implemented only with the assumption of adding inlay hints at the end of lines, since coc.nvim supported only `Neovim`.
Inlay hints are now supported in `Vim9`, so I adjusted the positions, etc.
https://user-images.githubusercontent.com/188642/186540451-d25117b8-ba0a-46c0-acfb-812c118460ff.mp4
https://user-images.githubusercontent.com/188642/186540467-a7c969b4-778d-4396-8403-c5db61fa7f25.mp4
> refactor(inlayHints): code changes for vim9 support

- src/features/linters/lintingEngine.ts
- src/types.ts
Some linters have support for error ranges (e.g. Ruff) which gives nicer diagnostics since they mark the entire error region instead of just the first character.
Before:
After:
Issue #853
> feat: add support for endLine/endColumn to linters

- src/features/linters/ruff.ts
Before:
After:
Depends on #854.
Fixes #853
> feat(ruff): include endLine and endColumn in diagnostics

- src/features/inlayHints.ts
Previously the inlay hint for variables would include a space at the end. This meant that if you had a space between the variable and =, two spaces would be displayed between the hint and =.
This looks pretty ugly imo, and means that with normal formatting there would be a different amount of spaces for the inlay hints and the explicit hints in the code.
Before:
After:
> Remove extra space after inlay hint for variables

- package.json
I have multiple projects in monolithic git repositories. These projects have somewhat of the following structure:
```
/project
- Has .git folder, .gitignore, etc
/bot - python discord bot
- Pipfile, bot.py, etc
/frontend - react, astro, whathave you
- misc js files (unimportant)
/[others]
```
Since these monorepos potentially have multiple python projects in them, each with their own Pipfile, I would like
pyright to be able to automatically find the venv for the sub folder containing the pipfile.
I have tried to do this on my own by adding a `pyrightconfig.json` with
```json
{
"executionEnvironments": [{
"root": "bot"
}
]
}
```
However this did not solve the problem, and seemed to have no effect.
I also tried overriding parts of coc-config / coc-local-config, However neither of these …
> feat: add Pipfile to rootPatterns in package.json

- src/features/linters/ruff.ts
support old and new format both
close #916
> fix(ruff): support new ruff fix format

- src/features/refactor.ts
We are creating unnecessary temp files If rope is not installed
> Check for rope before creating temp file

- package.json
Example layout:
xxx
├── project-a
│   └── setup.py
├── project-b
│   └── setup.py
├── pytest.ini
├── tox.ini
└── venv
└── pyvenv.cfg
Without the extra root patterns, the workspace root would be detected as `xxx/project-a` or `xxx/project-b`. Neither of them contains the `venv` directory.
> Add more root patterns for multi-modules workspace

- src/features/formatters/ruff.ts
Ruff now supports line ranges, so pass them through using the --range argument.
> Add range argument to Ruff formatter.

- src/configSettings.ts
[uv](https://docs.astral.sh/uv/) is a lately popular package management tool.
It creates `.python-version` and `.venv`.
This PR fixes to work with `uv` by adding some codes before ones for `pyenv`.
> Support uv

- src/parsers/testFramework.ts
In my workflow at work I sometimes have pytest test classes nested two classes deep, but as is I cannot run single tests within the nested test classes. This fixes the issue by looping all parent classes and adding their names to the fully qualified name passed to pytest. Tested locally with the following python pytests:
```python
def foo() -> None:
return None
def test_foo() -> None:
assert foo() is None
class TestFoo:
def test_toplevel_class_test(self) -> None:
assert foo() is None
class TestMethods:
def test_single_nested_level_class_test(self) -> None:
assert foo() is None
class TestRealFarIn:
def test_double_nested_level_class_test(self) -> None:
assert foo() is None
```
Each of these tests can be run individually with `pyright.singleTest` command after this fix.
I'm not 100% sure …
> fix: cannot run nested pytest test classes

- src/commands.ts
Sometimes importing a test framework such as pytest can trigger importing other code that has a longer runtime on import than allowed by the spawned process. This fixes the issue by checking that the import path can be found, which does not trigger importing the code.
> fix: checking unittest framework exists can be slow
